name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          pushd ../
          git clone https://github.com/Open-Controller/opencontroller-lib.git opencontroller-lib
          pushd opencontroller-lib
          yarn
          yarn build
          popd
          popd
          yarn
          yarn add ../opencontroller-lib
          ls node_modules|grep "opencontroller"
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          pushd ../
          git clone https://github.com/Open-Controller/opencontroller-lib.git opencontroller-lib
          pushd opencontroller-lib
          yarn
          yarn build
          popd
          popd
          yarn
          yarn add ../opencontroller-lib
          pushd android/app
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
          popd
      - name: Build Android Release
        run: |
          cd android && ENTRY_FILE=index.tsx ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
